name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点同步
  workflow_dispatch: # 可以手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        persist-credentials: false

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream
      run: git remote add upstream https://github.com/Stardm0/MoonTV.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream
      run: git merge upstream/main --allow-unrelated-histories

    - name: Push changes
      run: git push origin main
